name: Python Application CI
# Trigger workflow rerun to verify Python version matrix.
# Adding a comment to trigger a new workflow run and clear any caching issues.
# Attempting to trigger a new workflow run to resolve potential caching issues - 2023-05-10 12:00:00 UTC
# Attempting to resolve unexpected Python 3.1 job issue - 2023-05-11 14:30:00 UTC

on:
  push:
    branches: [ main, devin/fix-workflow-issue/11779 ]
  pull_request:
    branches: [ main, devin/fix-workflow-issue/11779 ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      timeout-minutes: 5
    - name: Display installed packages
      run: |
        pip list
    - name: Run tests
      run: |
        python -m unittest discover -v -s tests || (echo "Tests failed. See output above for details." && exit 1)